/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import sanityClient from "../utils/client";
import { motion } from "framer-motion";
import About from "../components/About";
import Contact from "../components/Contact";
import styled from "styled-components";
import Card from "../components/Card";

const BlogPostsGrid = styled.div`
  display: flex;
  flex-direction: column;
  margin: 20px 150px 10px 0;
  // background: pink;

  @media only screen and (max-width: 1024px) {
    margin: 0 0 0 30px;
    grid-template-columns: 1fr;
  }

  @media only screen and (max-width: 600px) {
    grid-template-columns: 1fr;
    margin: 5px;
  }
`;

const Home = ({ posts }) => {
  return (
    <>
      <Head>
        <title>The Indoor Jungle Project | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.  i1co" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        {/* //todo: create card component for each post
         */}
        <section id="latest-posts">
          <BlogPostsGrid>
            {posts &&
              posts.map((post, index) => (
                <span key={index}>
                  <>
                    <Card post={post} />
                  </>
                </span>
              ))}
          </BlogPostsGrid>
        </section>
        <About />
        <Contact />
      </motion.div>
    </>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const query = '*[_type == "posts"] | order(_createdAt asc)';
  const posts = await sanityClient.fetch(query);
  if (!posts.length) {
    return {
      props: {
        posts: [],
      },
    };
  } else {
    return {
      props: {
        posts,
      },
    };
  }
};
